markdown: rdiscount
permalink: /:title/
url: http://kuanghy.github.io/ 
name: Huoty's Blog 
author: Huoty
qq: 1346632121
email: sudohuoty@163.com
duoshuo: huoty
beian: 浙ICP备12026616号
cnzz: 119959
weibo: loveqing2013
github: kuanghy
highlighter: pygments
safe: true
paginate: 20
